### ISSUE TITLE
Does not accurately capture selection on scaled outputs.

### ISSUE THREAD

**Issue by XV-02** [pop-os/cosmic-screenshot#11]
While attempting to take screenshots for a scaling related issue for another Cosmic DE component, I noticed that cosmic-screenshot would not correctly capture the selected areas. I will need to look at how display- and window- capture modes behave as well. 

I was attempting to capture the right half (excluding the dock) of my desktop at three scales: 75%, 100%, and 125%.

In the 100% scaled screenshot, the area selected is correctly captured:

![screenshot-2024-02-24-00-35-40](https://github.com/pop-os/cosmic-screenshot/assets/98765732/fff4b7a9-c8c4-48e0-b279-2f4fc46f0fd5)

In the 75% screenshot, the image does not capture the clock, and is over-provisioned (screenshot captures the excess as transparent. I have filled it as light grey to prevent the image being truncated in-line). Effectively _both_ the left and right edges have been shifted rightwards by what I suspect is a linear multiple of the relative positions of the scaled pixels compared with the screen's actual pixel space. 
![screenshot-2024-02-24-00-35-04_mod](https://github.com/pop-os/cosmic-screenshot/assets/98765732/c53a801b-7183-4ef6-83f8-b773c9f94674)

In the 125% screenshot, the image does not capture the screenedge desired, and the capture spills over to the left of the selected area, indicating that the frame has at least shifted leftwards. The height captured is also shorter than was selected in the screenshot tool. However, the top edge of the image is at the top of the display, which the selection should be.
![screenshot-2024-02-24-00-36-04](https://github.com/pop-os/cosmic-screenshot/assets/98765732/31e46cb4-faa3-4de9-8619-c4fa2574d29e)

On all three screeshots, the area was selected by dragging the selection box from top-left to bottom-right. I have yet to test whether the direction of selection will have an impact.

**Comment by XV-02** [comment]
I would note that this seems to be the same issue as reported in https://github.com/pop-os/cosmic-screenshot/issues/5

**Comment by XV-02** [comment]
Individual window selection and full screen selection on scaled displays seems to be working as desired, I would note. It looks only to be an issue for arbitrary drag-box selection. It doesn't seem that the directionality of dragging the selection makes a difference.

**Comment by ryanabx** [comment]
I have the same issue on 200% scaling, and yes, it is exclusive to selecting a section to screenshot.

**Comment by XV-02** [comment]
It appears that, as of at least https://github.com/pop-os/cosmic-screenshot/commit/a8130eb9dc74ea8720240e3890a87b1fbe7f234f this has been resolved.
