### ISSUE TITLE
saves to dirs that don't exist, doesn't make them

### ISSUE THREAD

**Issue by colemickens** [pop-os/cosmic-screenshot#17]
See title.

I can't really get cosmic-screenshot (the GUI) to do anything useful whatsoever.

It shows two places to save pictures, neither of which exist, neither of which are created when I try to take a screenshot. It also does not let me choose where to save them.

**Comment by colemickens** [comment]
Also, `--save-dir` / `-s` is ignored if the user doesn't pass `--interactive=false`.

I kinda feel like `--interactive=false` would be a nice default when launched from cli.

**Comment by colemickens** [comment]
somewhat overlaps with #14, but maybe this one can be closed with a `mkdir -p` for the selected save dir.

(I might try my hand at some fixes, if anyone has quick guidance on the "best" "right" fix. Aka, "just mkdirp it", etc)

**Comment by WatchMkr** [comment]
Duplicate of #13. Tracking there.
