### ISSUE TITLE
icons aren't loaded for the toolbar

### ISSUE THREAD

**Issue by colemickens** [pop-os/cosmic-screenshot#18]
![Screenshot_2024-04-15_20-07-03](https://github.com/pop-os/cosmic-screenshot/assets/327028/31c89127-d66e-4429-b2ed-f5979ad265ff)

(ignore my fun alacritty/toml adventures in the background)

**Comment by lukejcollins** [comment]
Also experiencing this issue

**Comment by jh-devv** [comment]
Experiencing this too!

**Comment by athre0z** [comment]
Everyone posting in this thread, including myself, appears to be a NixOS user. Might be a packaging issue?

**Comment by athre0z** [comment]
I looked into this a bit more. It appears that the NixOS flake is expecting that the `cosmic-icons` repo provides all the icons. However, in case of the screenshot UI, the icons only live in [`xdg-desktop-portal-cosmic` repo](https://github.com/pop-os/xdg-desktop-portal-cosmic/tree/master/data/icons/scalable/actions), but aren't duplicated in `cosmic-icons`. Not sure what the policy is on that and whether that is an oversight.

**Comment by Elias-Graf** [comment]
(As an external person, this seems like an oversight to me.) It doesn't really make sense to have icons in the portal, right?
@athre0z I haven't looked into how the icons are "loaded" / "provided" in the package, but would it be possible, as a workaround, to add the portal as an "icon dependency" in the flake for the time being?

**Comment by athre0z** [comment]
> It doesn't really make sense to have icons in the portal, right?

It seems that all other icons are duplicated in two places: the component where they are used and the `cosmic-icons` repository. While the portal may seem weird on first glance, it actually makes sense: the screenshot tool in this repo here is just a small util that sends a message to the portal, asking it to trigger a screenshot. The actual drawing logic using the logo lives in the portal code. So the question is: should every icon always be duplicated in the icons repo, or must packagers make sure to also make the icons from each individual component available?

> but would it be possible, as a workaround, to add the portal as an "icon dependency" in the flake for the time being?

Yeah, almost definitely should be possible. I may take a look and attempt a PR against the NixOS cosmic flake repo sometime next weekend, though no promises.

**Comment by Elias-Graf** [comment]
> it actually makes sense: the screenshot tool in this repo here is just a small util that sends a message to the portal
Yeah, that's true, but IMO the portal should just include the icon repo, instead of hosting them itself.

**Comment by athre0z** [comment]
It appears that this has been fixed in the flake in https://github.com/lilyinstarlight/nixos-cosmic/commit/d065ae2b8198d4236c474470214a6aadb6a521bf. The icons are showing up correctly for me now.
