### ISSUE TITLE
[Issue] Rotated displays do not get captured correctly.

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/cosmic-screenshot#25]
If you take a screenshot of a rotated display it has issues like in the screenshot.

![screenshot-2024-05-29-17-17-06](https://github.com/pop-os/cosmic-screenshot/assets/4884946/8c736176-15d8-43be-8170-faf52409b57b)

**Comment by Gr3q** [comment]
Also a part of the rotated screen will be shown rotated again on top of the same screen along with the overlay, at least for me.

**Comment by WatchMkr** [comment]
Tracking here: https://github.com/pop-os/cosmic-screenshot/issues/46
