### ISSUE TITLE
Cosmic screenshot doesn't work

### ISSUE THREAD

**Issue by gantryyork** [pop-os/cosmic-screenshot#3]
The GUI for cosmic-screenshot can not be launched from the launcher

The cli for cosmic-screensheet run from the command line results in the following error

thread 'main' panicked at src/main.rs:20:10:
failed to receive screenshot response: Response(Other)

**Comment by gantryyork** [comment]
cosmic-screenshot works.  GUI comes up.
I can launch it from the command line
I can launch it from the launcher

It would be nice if  it were mapped to the print screen key by default

**Comment by gantryyork** [comment]
And now it's not working again.  I get the same "thread 'main' panicked" error again.

**Comment by gantryyork** [comment]
It also no longer seems to launch from the Launcher

**Comment by gantryyork** [comment]
After taking the screenshot, I am unable to paste with either right click or ctrl-v

**Comment by XandrCopyrighted** [comment]
`> cosmic-screenshot`
thread 'main' panicked at src/main.rs:69:10:
failed to send screenshot request: Zbus(MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.UnknownMethod")))), Some("No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop"), Msg { type: Error, sender: UniqueName(Str(Borrowed(":1.36"))), reply-serial: 17, body: Signature("s") }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by XandrCopyrighted** [comment]
fixed: add `XDG_CURRENT_DESKTOP=cosmic` to your [environment variable](https://wiki.archlinux.org/title/Environment_variables#Globally)

**Comment by TheKamboy** [comment]
> fixed: add `XDG_CURRENT_DESKTOP=cosmic` to your [environment variable](https://wiki.archlinux.org/title/Environment_variables#Globally)

This didn't work for me.

**Comment by XandrCopyrighted** [comment]
> This didn't work for me.

that's odd, try adding it to `/etc/environment` then reboot

**Comment by XandrCopyrighted** [comment]
That worked for me, well on Arch Linux

**Comment by TheKamboy** [comment]
> > This didn't work for me.
> 
> that's odd, try adding it to `/etc/environment` then reboot

thats exactly what i did, and it doesn't work (yes i rebooted)

**Comment by TheKamboy** [comment]
> That worked for me, well on Arch Linux

i am using arch linux

**Comment by XandrCopyrighted** [comment]
odd

**Comment by ProjectInfinity** [comment]
Can confirm that adding XDG_CURRENT_DESKTOP=cosmic to /etc/environment and rebooting does **not** work.

```
❯ cosmic-screenshot
thread 'main' panicked at src/main.rs:71:10:
failed to receive screenshot response: Response(Other)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

~
❯ cat /etc/environment
#
# This file is parsed by pam_env module
#
# Syntax: simple "KEY=VAL" pairs on separate lines
#
XDG_CURRENT_DESKTOP=cosmic
```

**Comment by fstanis** [comment]
Since this thread comes up on top when searching for the errors, just wanted to summarize the solution since I just experienced both of them.

- If the error is `failed to send screenshot request: ...`, `XDG_CURRENT_DESKTOP` is unset or set to the wrong value
- If the error is `failed to receive screenshot response: ...`, `XDG_CURRENT_DESKTOP` is set to `cosmic` (lowercase) whereas it should be `COSMIC` (uppercase)

Either way, the solution is to make sure `/etc/environment` contains `XDG_CURRENT_DESKTOP=COSMIC`. A restart is required, i.e. it's not enough to just set it in the current session.
