### ISSUE TITLE
failed to send screenshot request

### ISSUE THREAD

**Issue by AliothCancer** [pop-os/cosmic-screenshot#41]
I installed cosmic on pop 22.04 with apt, I also have default gnome-cosmic installed. If you need more infos, I'll be glad to give you.

> sudo cosmic-screenshot
thread 'main' panicked at src/main.rs:69:10:
failed to send screenshot request: Zbus(InputOutput(Os { code: 2, kind: NotFound, message: "No such file or directory" }))

❯ cosmic-screenshot
thread 'main' panicked at src/main.rs:71:10:
failed to receive screenshot response: Response(Other)
stack backtrace:
   0:     0x55cd2cb171a5 - <unknown>
   1:     0x55cd2cb3d21b - <unknown>
   2:     0x55cd2cb1419f - <unknown>
   3:     0x55cd2cb16f7e - <unknown>
   4:     0x55cd2cb18239 - <unknown>
   5:     0x55cd2cb17f7d - <unknown>
   6:     0x55cd2cb186d3 - <unknown>
   7:     0x55cd2cb185b4 - <unknown>
   8:     0x55cd2cb17669 - <unknown>
   9:     0x55cd2cb182e7 - <unknown>
  10:     0x55cd2c8715f3 - <unknown>
  11:     0x55cd2c871aa6 - <unknown>
  12:     0x55cd2c8961b4 - <unknown>
  13:     0x55cd2c98021b - <unknown>
  14:     0x55cd2c9624fb - <unknown>
  15:     0x55cd2c9803b3 - <unknown>
  16:     0x55cd2c962b21 - <unknown>
  17:     0x55cd2c936edc - <unknown>
  18:     0x55cd2c9701b8 - <unknown>
  19:     0x55cd2c92a703 - <unknown>
  20:     0x55cd2c947ef9 - <unknown>
  21:     0x55cd2cb0f0e0 - <unknown>
  22:     0x55cd2c970285 - <unknown>
  23:     0x7a2733029d90 - <unknown>
  24:     0x7a2733029e40 - __libc_start_main
  25:     0x55cd2c871d45 - <unknown>
  26:                0x0 - <unknown>

**Comment by lifeiscontent** [comment]
seems like it runs fine under sudo, you just need to specify the directory of where you want the screenshot saved

**Comment by AliothCancer** [comment]
I now ditched pop 22.04 for nobara 40, im gonna install cosmic, I think this problem was caused by the coexistence of gnome and cosmic, I had also other problems like some applet-library-a and applet-launcher costantly taking 100% of one thread, and terminating them was ok, also at the DE start, cosmic-notfier wasn't starting, I booted cosmic from gdm3 cause cosmic-greeter after an update released about 1 week ago couldn't let me access.

So i'll report if I get problems on my new nobara 40 on which I have also kde installed.
