### ISSUE TITLE
gnome-screenshot does not work on cosmic desktop

### ISSUE THREAD

**Issue by soloturn** [pop-os/cosmic-screenshot#43]
what i find funny, for me gnome-screenshot (the old one, not gnome4 integrated in shell one) does not work on cosmic desktop. why is this so? on arch linux, logging into cosmic via GDM.

**Comment by mmstick** [comment]
Because COSMIC is not GNOME. COSMIC already has its own native screenshot utility. `cosmic-screenshot`. It also has its own COSMIC Screenshot desktop entry.
