### ISSUE TITLE
Cropping screenshot doesn't work with fractional scale display

### ISSUE THREAD

**Issue by Quackdoc** [pop-os/cosmic-screenshot#5]
When performing a screenshot with `cosmic-screenshot` performing monitor or window screen capture will work fine, however when using a cropping screenshot, the coordinates don't seem to get updated properly, causing the clipped region to be offset. Temporarily resetting the scale to 1.0 to take the screenshot can work around the issue.

**Comment by WatchMkr** [comment]
This appears to be fixed.
