### ISSUE TITLE
[Bug] Panics when attempting to launch

### ISSUE THREAD

**Issue by drazil100** [pop-os/cosmic-screenshot#52]
My system is running Manjaro (Cinnamon edition) and recently I installed cosmic-session-git through the AUR. I have been unable to use cosmic-screenshot since I installed the DE. I am not sure if I am missing a dependency, or if something on my system is configured weird, or if it's just broken.

```
$ cosmic-screenshot
thread 'main' panicked at src/main.rs:69:10:
failed to send screenshot request: Zbus(MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.UnknownMethod")))), Some("No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop"), Msg { type: Error, sender: UniqueName(Str(Borrowed(":1.58"))), reply-serial: 17, body: Signature("s") }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by WatchMkr** [comment]
tracking here: https://github.com/pop-os/cosmic-screenshot/issues/42
