### ISSUE TITLE
After update can no longer copy to clipboard

### ISSUE THREAD

**Issue by Quackdoc** [pop-os/cosmic-screenshot#72]
Cosmic-screenshot does not report any errors nor are there issues being logged in journald

Saving to pictures and saving to documents both work

**Comment by Xionical1** [comment]
I get 
```
cosmic-comp[1211]: Failed to request current wayland clipboard for Xwayland.
```

in my journal whenever I try to paste the screenshot. In vesktop it recognizes the paste as an image (or so I think), but the preview is gray and returns an error if I try posting.
